### ISSUE TITLE
simulation crashing 201_Taylor_couette

### ISSUE THREAD

**Issue by SaumiliJana** [cselab/aphros#12]
Dear Aphros team,

Greetings. Recently, I started exploring Aphros simulations and found an example 201_Taylor_couette crashing while outputting the data. The std.conf file consists of the following dump information. It is neither dumping such data for further visualization using paraview or other software. Could you kindly respond. And also, how to understand these dumpbc, dumplist, 1e10 etc variable. Any manual which clearly explain these examples. Thank you. 

# dump
set int dumpbc 1
set string dumplist vx vy p div
set double dump_field_dt 1e10
set double dump_field_t0 1e10
set int report_step_every 1
set int stat_step_every 1
set double dump_trep_t0 1e10
set int verbose_stages 0
set int dumplast 1

**Comment by pkarnakov** [comment]
Hi, 

I have fixed some parameters and code, the example should run now.
https://github.com/cselab/aphros/blob/master/examples/201_taylor_couette/README.md

Please see https://github.com/cselab/aphros/blob/master/deploy/scripts/sim_base.conf
for descriptions of the parameters (also copied to `base.conf` in the simulation directory).

Thanks for this report!
