### ISSUE TITLE
How do I setup Liquid drops impact simulations?

### ISSUE THREAD

**Issue by govindiitd** [cselab/aphros#15]
I am exploring the aphros for drop and bubble dynamics. I find the "https://cselab.github.io/aphros/wasm/hydro.html" as good starting point. Example "107_wasm" is the right one to start? I see each example has different way to setting up the basic simulation. 

To get the basic of the aphros, if I start with simple simulation like lid-driven or flow-over cylinder, as in aphros-explorer' , to drop impact.  Is there any full detailed test case is available?

**Comment by pkarnakov** [comment]
have you seen the case [Drop impact without coalescence](https://cselab.github.io/aphros/wasm/aphros.html?config=M4UwLgBMYE4JYDsDmExzAGxBARAERgHsAHCOAW2IEMBjMHAKAdEmnmQgDc5gBXKjLgadCMNDXQBPCAG8GEKOC4g6XAbxDAIAWgCMABgiGD8xZE4rINQhlFaAJAGEARhg0QnAdwAW6bE5gQABMGAF8mETdybAAzGFo0QgRZUxZlVU51TSMIXVSlC1VrWxgHRyRAkGSnCpAq_PNLCBJadDhsw30AOgBWMIZGZiUgwl5XbBAADzAqyDy0xEhvSWJAgH1iEHhCILgaNcncodZYRBREdDXOGIgMHjBjqFOOO-gNqjBvXEQ7hBBTZyEQ6dHIGIy9IypYjeLbYbo9cEADhy3V0fUGaRGYywEBg3kIuiOmNG41x-IATBByY8saTyLxCd19PNhiScfTKUzqcTsdhgHAkOQqOCWZBaTiUHp9AwAGIAJQA8gBZADKABkAJJ4ACicrM6UgFSo3DA0kM9iQTB5pJoMQw0HBfTSbDOECoQUKiQQa2ANgsMC4hBi5CtShdHGAdyCWy0jAUkrBYKNJskqQFQtBUF4MBitGwMwQ_KSAyAA===)  in [explorer](https://github.com/cselab/aphros/wiki/Aphros-Explorer) ?

**Comment by govindiitd** [comment]
Yes I see. I want to setup on my system such that I can start to debug. I am trying to get it, but if anything that you can suggest or guide, will help me a lot.

**Comment by pkarnakov** [comment]
the easiest case to try locally is [examples/202_coalescence/2d](https://github.com/cselab/aphros/tree/master/examples/202_coalescence/2d)
