### ISSUE TITLE
Output parameters 

### ISSUE THREAD

**Issue by fgxti** [cselab/aphros#16]
Greetings Aphros team!
We are using Aphros to research foam. We encountered some problems and hope you can help us.
1.	We would like to know which parameters of the foam can be obtained if the foam is studied. For example, the size or distribution of the foam over time. We would appreciate it if you could tell us in detail what foam parameters are available or how to set up to access the parameters that are available
2.	We have run some examples and imported the resulting .vtk file into paraview, and we found that only the information with the names cl, l and c could be visualized, and we wanted to know what each of these three parameters meant. And we found that not all examples have the three parameters in the output files (.vtk) and . We would like to know how these parameters are set up for export to .vtk files, are they defined in a file? Please explain in more detail
We look forward to your response!
Thank you

**Comment by fgxti** [comment]
Hi，Dr.karnakov. Thank you for your answer, it was very helpful. We still have some questions that we are looking forward to your answers.
1. We are a bit confused about extent.
(1) Is extent built from (0.0.0) ?
(2) Regarding the waterfall example, the supplementary materials  of the 11th reference you provided (Computing foaming flows across scales: From breaking waves to microfluidics) describes domain width=100mm, but in the source code example the extent is 200mm, and there is no wall set in the width direction to limit it, so should the domain width be 200mm?
(3) Regarding the Clustering example, the supplementary materials describes the domain height=20 mm , while the extent in the source code example is 30 mm. We only find the centre of the box in the y-direction is 20 in the b.dat file. What should we understand by domain and extent?
2. We have tried to simulate waterfall and Clustering in the example, if we use the settings of m=32 32 32 and np=4 (in computer A), there will be a situation where the liquid will appear in the upper part of the computational domain and the liquid above will fall into the lower part of the liquid and interfere with the lower part of the liquid, while with the number of grids you provide and increasing the number of np (in the server B) it will not appear.  What is the reason for this. We have included pictures here so that you can better understand our problem. The AB in the file name represents the two cases of running in the computer AB respectively.
![cluster-A](https://github.com/cselab/aphros/assets/134249554/d9192a74-30d4-4d56-b719-f7d9ed7d78ff)
![cluster-B](https://github.com/cselab/aphros/assets/134249554/af05ce10-64f1-44c8-af81-5eee85a34896)
![waterfall-A](https://github.com/cselab/aphros/assets/134249554/f64f4129-851b-4609-88d0-792fe793a580)
![waterfall-B](https://github.com/cselab/aphros/assets/134249554/a2bd13bc-c00c-49e7-be95-c982fa939065)

3.Thanks again for the answers to our last questions. We have studied the traj_*.csv file and we understand that cl, p, vf, v, x, y, z are the colour value, pressure inside the bubble, volume fraction, velocity and bubble position respectively, but we don't quite understand what xx, xy, xz, yz, zz mean, what does each mean?
We look forward to your answers again. Thanks again!

**Comment by fgxti** [comment]
Hi，Dr.karnakov. Thank you for your answer, it was very helpful. We still have some questions that we are looking forward to your answers.

1、We are a bit confused about extent.
(1) Is extent built from (0.0.0) ?
(2) Regarding the waterfall example, the supplementary materials of the 11th reference you provided (Computing foaming flows across scales: From breaking waves to microfluidics) describes domain width=100mm, but in the source code example the extent is 200mm, and there is no wall set in the width direction to limit it, so should the domain width be 200mm?
(3) Regarding the Clustering example, the supplementary materials describes the domain height=20 mm , while the extent in the source code example is 30 mm. We only find the centre of the box in the y-direction is 20 in the b.dat file. What should we understand by domain and extent?
2、We have tried to simulate waterfall and Clustering in the example, if we use the settings of m=32 32 32 and np=4 (in computer A), there will be a situation where the liquid will appear in the upper part of the computational domain and the liquid above will fall into the lower part of the liquid and interfere with the lower part of the liquid, while with the number of grids you provide and increasing the number of np (in the server B) it will not appear. What is the reason for this. We have included pictures here so that you can better understand our problem. The A and B in the file name represents the two cases of running in the computer A and B respectively.
![cluster](https://github.com/cselab/aphros/assets/134249554/fe066a50-3bc4-4636-94a0-089f536389e0)
![waterfall](https://github.com/cselab/aphros/assets/134249554/c34cbc9d-4e53-44a4-93e9-2413008d1c5d)

3.Thanks again for the answers to our last questions. We have studied the traj_*.csv file and we understand that cl, p, vf, v, x, y, z are the colour value, pressure inside the bubble, volume fraction, velocity and bubble position respectively, but we don't quite understand what xx, xy, xz, yz, zz mean, what does each mean?
We look forward to your answers again. Thanks again!

**Comment by pkarnakov** [comment]
sorry for a late reply,

> 1. We are a bit confused about extent.
> (1) Is extent built from (0.0.0) ?

Yes, extent is the largest size of the three (in x,y,z)

> (2) Regarding the waterfall example, the supplementary materials of the 11th reference you provided (Computing foaming flows across scales: From breaking waves to microfluidics) describes domain width=100mm, but in the source code example the extent is 200mm, and there is no wall set in the width direction to limit it, so should the domain width be 200mm?

the extent in this case is the length of the domain, which is twice as large as its width

> (3) Regarding the Clustering example, the supplementary materials describes the domain height=20 mm , while the extent in the source code example is 30 mm. We only find the centre of the box in the y-direction is 20 in the b.dat file. What should we understand by domain and extent?

here the largest size is the height

> 2. We have tried to simulate waterfall and Clustering in the example, if we use the settings of m=32 32 32 and np=4 (in computer A), there will be a situation where the liquid will appear in the upper part of the computational domain and the liquid above will fall into the lower part of the liquid and interfere with the lower part of the liquid, while with the number of grids you provide and increasing the number of np (in the server B) it will not appear. What is the reason for this. We have included pictures here so that you can better understand our problem. The A and B in the file name represents the two cases of running in the computer A and B respectively.

the grid size determines the proportions of the domain (by default m="192 128 192"), so if you want to run on a coarser grid, you should keep the same proportions (e.g. m="48 32 48")

> 3.Thanks again for the answers to our last questions. We have studied the traj_*.csv file and we understand that cl, p, vf, v, x, y, z are the colour value, pressure inside the bubble, volume fraction, velocity and bubble position respectively, but we don't quite understand what xx, xy, xz, yz, zz mean, what does each mean?

xx, xy and are the second moments of the volume fraction, which can be used to compute the gyration tensor and e.g. fit an ellipsoid to the bubble
they are computed here https://github.com/cselab/aphros/blob/master/src/util/hydro.ipp#L1100

**Comment by fgxti** [comment]
Thank you for your response to our question, we have been able to run it successfully based on your instructions, but we still have some confusion in running it.
1. In the clustering example, we unset the x,z direction as the periodic boundary, which will result in the presence of water on the surrounding boundary and the water phase in the box will increase, why does this happen when the periodic boundary setting is turned off? Where does the water in this case come from? We have attached the relevant images, showing the states at 0.33s and 3.27s respectively.
![1](https://github.com/cselab/aphros/assets/134249554/20ac930d-af55-47e6-91a8-3b3412e4bc61)

2. About dumplist setting we find that we can set omm and k. What are these three respective quantities? We find the options about dumplist setting in the files base.conf and hydro_post.ipp. What other variables are available about dumplist besides that?
3、We want to simulate the bubble situation at the stern of the boat when it is moving in the water and the gas-liquid situation when an object like a paddle is inserted vertically into the water and rotated and stirred, can these two situations be simulated by this software setting( For example, by setting the boundary conditions, we find that we can set the rotatable wall in init_bc.h. Please give some setup instructions if it is possible)?
4、Can the calculation continue at the stopping point when aphros is stopped? How do I do this?
Looking forward to your reply again
