### ISSUE TITLE
 How to output the velocity field in VTK format？

### ISSUE THREAD

**Issue by Lidabao77** [cselab/aphros#17]
Dr. Karnakov，When I was studying example 205，examples/205_multivof/clustering，what should I do to output the velocity field in vtk format.Thank you

**Comment by pkarnakov** [comment]
If you append `std.conf` or `add.conf` with the following lines
```
set string dumplist vx vy vz
set string dumpformat raw
```
the solver will write the velocity fields to `*.xmf` (metadata) and `*.raw` (binary data). VTK is not supported for the fields. 
The default parameters with some descriptions are in [deploy/scripts/sim_base.conf)](https://github.com/cselab/aphros/blob/master/deploy/scripts/sim_base.conf). I've also extended [examples/README.md](https://github.com/cselab/aphros/tree/master/examples#configuration)

**Comment by Lidabao77** [comment]
I see, thank you for your answer

**Comment by Moxing529** [comment]
Hello Lidabao77，I am also studying Example 205 in examples/205_multivof/clustering. I used the dumplist to output the pressure field, resulting in XMF and RAW format files. Could you please let me know how you view these two files? I always encounter errors when trying to open them in ParaView. Thank you!
