### ISSUE TITLE
How to make the s*.vtk export look smoother?

### ISSUE THREAD

**Issue by Lidabao77** [cselab/aphros#19]
Dr. Karnakov, the s*.vtk file outputs different volume fractions of the contour, but it looks rough in paraview, how to make it smooth?
![bubble](https://github.com/user-attachments/assets/42ebdc92-1aea-4bb2-9c8b-b392eefc486c)

**Comment by pkarnakov** [comment]
Hi, the smooth surfaces are written to sm_*.vtk if parameter dumppolymarch
equals 1 (which is the default).

**Comment by Lidabao77** [comment]
Problem solved, thanks for the answer!
