### ISSUE TITLE
how to start first case

### ISSUE THREAD

**Issue by DSDS-CMHL** [cselab/aphros#9]

**Comment by pkarnakov** [comment]
After setting up the environment with `. ap.setenv`, try running one of the examples
[examples/202_coalescence](https://github.com/cselab/aphros/tree/master/examples/202_coalescence).
```
make m="64 64 64" np=1 run 
```
This will run the case on a mesh of `64^3` cells and 1 processor. See `Makefile` for a description of parameters.
I plan to write a small tutorial, please let me know if the command above works for you.

**Comment by DSDS-CMHL** [comment]
> After setting up the environment with `. ap.setenv`, try running one of the examples [examples/202_coalescence](https://github.com/cselab/aphros/tree/master/examples/202_coalescence).
> 
> ```
> make m="64 64 64" np=1 run 
> ```
> 
> This will run the case on a mesh of `64^3` cells and 1 processor. See `Makefile` for a description of parameters. I plan to write a small tutorial, please let me know if the command above works for you.

Thanks for your reply, Dr.pkarnakov, I will try that. By the way, I am a phd candidate majoring in fluid mechanics, this is my first year. Your work is amazing, I hope I could learn from you.

**Comment by DSDS-CMHL** [comment]
>Hi, doctor. I tried to build without MPI, and run the case as you suggested, But there are some other problems.

Then I download the .zip source code aphros-master, And I build aphros in standard process which was written in /deploy/readme.md and the github page, this time I run the case and open the VTK files in paraview successfully.

Before that I uninstall the anaconda3 and remove it from my path environment. And I'm sure that I followed the recommend process every time I build aphros. So maybe when the file: libmpi.12.so exists in two different directions will cause some problem or the .zip source code is different from git clone. Personally, I think the latter is less likely.

Thanks for your time again,doctor. That's really help a lot.

**Comment by liyuhan930** [comment]
Hi, Dr. Karnakov. When I input "make m="64 64 64" np=1 run ", it always display "make: *** No rule to make target 'run'.  Stop" on the terminal. How to solve it? I hope I could learn from you.

**Comment by pkarnakov** [comment]
> Hi, Dr. Karnakov. When I input "make m="64 64 64" np=1 run ", it always display "make: *** No rule to make target 'run'. Stop" on the terminal. How to solve it? I hope I could learn from you.

Before running any simulations, you need to setup the environment by
```
. ap.setenv
```
(make sure that `~/.local/bin/ap.setenv` exists)

**Comment by liyuhan930** [comment]
Thanks, but I have got  "ap.setenv" in ~/.local/bin/. This question still exists.

**Comment by pkarnakov** [comment]
Then if you run
```
. ap.setenv
```
it should print something like
```
APHROS_SETENV=1
APHROS_PREFIX=/home/...
APHROS_PROFILE=default
```

**Comment by WQ199806** [comment]
Hi, Dr. Karnakov. In [examples/202_coalescence]. When I run
`. ap.setenv`
it will print the environment
`APHROS_SETENV=1
 APHROS_PREFIX=/home/...
 APHROS_PROFILE=default`
When I input "make m="64 64 64" np=1 run ", it always display 
`make: ap.makesim: Command not found`
`make: *** No rule to make target 'run'. Stop`
on the terminal. 

I have built a Docker container and run the examples_202_coalescence successfully. So far, I have not been able to successfully build the "Aphros" in my system.  I would be grateful/thankful if you could tell me how to solve it. I would appreciate your help.

**Comment by pkarnakov** [comment]
the two command have to be run in the same session,
apparently you do separate docker runs for each command,

how about something like:
```
. ap.setenv ; make m="64 64 64" np=1 run 
```

**Comment by WQ199806** [comment]
Hi, Dr. Karnakov. I tried your suggestion, but the results didn't change. It is still printed: 
`APHROS_SETENV=1`
`APHROS_PREFIX=/home/...`
`APHROS_PROFILE=default`
`make: ap.makesim: Command not found`
`make: *** No rule to make target 'run'. Stop`
I built the "Aphros" following the standard process of /deploy/readme.md.

**Comment by pkarnakov** [comment]
can you show the output of
```
. ap.setenv
echo "${APHROS_PREFIX}"
ls "${APHROS_PREFIX}/bin"
```

**Comment by pkarnakov** [comment]
`${APHROS_PREFIX}/bin` is supposed to contain more files,
can go to `deploy/build` and show the output of `make install` ?

**Comment by WQ199806** [comment]
Hi, Dr. Karnakov. I re-installed Aprhos after yesterday's discussion. This time I managed to run  the examples_202_coalescence.
Unlike my previous installation, I copied the `ap.setenv` file to the [/usr/local/bin/] directory.This allowed me to successfully set up the environment.
run 
`. ap.setenv`
output
`APHROS_SETENV=1`
`APHROS_PREFIX=/home/wq/Documents/aphros/deploy/PREFIX`
`APHROS_PROFILE=default`

This time when I run the command. 
`echo "${APHROS_PREFIX}" ; ls "${APHROS_PREFIX}/bin"`
output
`ap.aconf             ap.findsource  ap.job        ap.scale
ap.applycopyright    ap.format      ap.job0       ap.setenv
ap.argmax            ap.genxmf      ap.kedr       ap.sim_base.makefile
ap.argmaxall         ap.genxmfall   ap.kill       ap.spawn
ap.base              ap.getcol      ap.line       ap.statcopy
ap.cawk              ap.gettraj     ap.makearg    ap.submit
ap.conf2py           ap.gettrajcol  ap.makesim    ap.submit0
ap.copyright         ap.gettrajm    ap.mfer       ap.sysinfo
ap.create_a_conf     ap.gettrajsh   ap.mpirun     ap.task
ap.create_base_conf  ap.getval      ap.order      ap.trajaxes
ap.deriv             ap.gitsnap     ap.part       ap.vtkcolorall
ap.diff              ap.hausdorff   ap.part0      ap.writearg
ap.diffnum           ap.hist        ap.plain2vtk  paratools
ap.downsample        ap.histbin     ap.pngmp4     plottools
ap.downsampleall     aphros         ap.run        t.advection
ap.explorer          ap.intcol      ap.run0       t.embed_interpolate`

I‘m truly greatful for your help!

**Comment by liyuhan930** [comment]
> Hi, Dr. Karnakov. I re-installed Aprhos after yesterday's discussion. This time I managed to run the examples_202_coalescence. Unlike my previous installation, I copied the `ap.setenv` file to the [/usr/local/bin/] directory.This allowed me to successfully set up the environment. run `. ap.setenv` output `APHROS_SETENV=1` `APHROS_PREFIX=/home/wq/Documents/aphros/deploy/PREFIX` `APHROS_PROFILE=default`
> 
> This time when I run the command. `echo "${APHROS_PREFIX}" ; ls "${APHROS_PREFIX}/bin"` output `ap.aconf ap.findsource ap.job ap.scale ap.applycopyright ap.format ap.job0 ap.setenv ap.argmax ap.genxmf ap.kedr ap.sim_base.makefile ap.argmaxall ap.genxmfall ap.kill ap.spawn ap.base ap.getcol ap.line ap.statcopy ap.cawk ap.gettraj ap.makearg ap.submit ap.conf2py ap.gettrajcol ap.makesim ap.submit0 ap.copyright ap.gettrajm ap.mfer ap.sysinfo ap.create_a_conf ap.gettrajsh ap.mpirun ap.task ap.create_base_conf ap.getval ap.order ap.trajaxes ap.deriv ap.gitsnap ap.part ap.vtkcolorall ap.diff ap.hausdorff ap.part0 ap.writearg ap.diffnum ap.hist ap.plain2vtk paratools ap.downsample ap.histbin ap.pngmp4 plottools ap.downsampleall aphros ap.run t.advection ap.explorer ap.intcol ap.run0 t.embed_interpolate`
> 
> I‘m truly greatful for your help!

Hi, bro! Shall we communicate in Chinese? 兄弟，你是中国人吗？我们可以用汉语交流吗？

**Comment by DSDS-CMHL** [comment]
@liyuhan930 @WQ199806 
qq group 1020830956

**Comment by SaumiliJana** [comment]
Hi! I have been able to install aphros and run a few examples successfully. I wanted to do a scaling study of the example ‘clustering’ in the ‘205_multivof’ example directory. What all parameters should I change or take care of to change the number of processors keeping other parameters such as mesh size, resolution, etc same? Also how to change the size of the box in which the bubbles are risisng? Any help would be realy appreciated. Thanks
